### ISSUE TITLE
File Size Limit For OpenIV

### ISSUE THREAD

**Issue by sollaholla** [neos7/GTAV_Map_Helper#1]
Since there's a file size limit in open iv (somewhere upwards of 2MB I think), would it be possible to split the grass files when exporting? It'd be a great feature and save a lot of time 😄

**Comment by neos7** [comment]
The limit is for the .xml or the raw .ymap? I've exported 22k instances in a 12MB .xml and OpenIV converted it to .ymap (200Kb) without problems.

**Comment by neos7** [comment]
@sollaholla also [this](https://github.com/neos7/MapTools) allows to grid split the .xml once exported.

**Comment by sollaholla** [comment]
I should correct myself and say it does actually work in game fine, and in CW. The only thing that is weird is that it crashes OpenIV when I open it. But I guess since it's working fine it's not a big deal. Thanks for the XML splitter link too!
